# Generated by Django 2.1.5 on 2019-06-28 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Docname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=50)),
                ('doc_text', models.TextField(blank=True, max_length=250)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_slug', models.SlugField()),
                ('doc_creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Taskname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_text', models.TextField(verbose_name='submission')),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=4)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_status', models.IntegerField(choices=[(0, 'Submitted'), (1, 'Approved'), (2, 'Disapproved')], default=0)),
                ('docname', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='report.Docname')),
                ('input_contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
