# Generated by Django 2.1.5 on 2019-02-22 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taskname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_text', models.TextField(verbose_name='submission')),
                ('input_contributor', models.CharField(max_length=40)),
                ('edit_contributor', models.CharField(default='None', max_length=40)),
                ('hours_worked', models.DecimalField(decimal_places=1, max_digits=4)),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_status', models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Complete')], default=0)),
            ],
        ),
    ]
