# Generated by Django 2.1.5 on 2019-04-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskname',
            name='task_selected',
            field=models.BooleanField(default=False),
        ),
    ]
