# Generated by Django 2.1.5 on 2019-07-21 22:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190721_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docname',
            name='contributor',
            field=models.ManyToManyField(blank=True, related_name='doc_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='docname',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='doc_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
