# Generated by Django 2.1.5 on 2019-04-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_taskname_task_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskname',
            name='task_selected',
        ),
    ]
