# Generated by Django 2.1.5 on 2019-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190710_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profilePics/chewbaccaheadshot.jpeg', upload_to='profilePics/'),
        ),
    ]
