# Generated by Django 2.1.5 on 2019-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190718_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='report/chewbaccaheadshot.jpeg', upload_to='profilePics/'),
        ),
    ]
